[package]
name = "oauthmux-provider-ssm"
description = "AWS SSM Parameter Store configuration provider for oauthmux"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["aws"]
aws = ["dep:aws-sdk-ssm"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
aws-sdk-ssm = { workspace = true, optional = true }
oauthmux-core = { path = "../oauthmux-core" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
